### PR TITLE
Added logic to handle scenarios when views is set to an array

### PR DESCRIPTION
**Pull request by digita1-Anal0g**
If the views setting of Express is set to an Array, path.resolve will throw new TypeError('Arguments to path.resolve must be strings') and so I made adjustments to accommodate for that scenario.

### CODE REVIEW

**Comment by chrisyip** [comment]
@digita1-Anal0g Thank you for this PR! But this PR can't pass CI, could you fix it and add more tests to make code coverage to 100%? Thanks again!

**Comment by digita1-Anal0g** [comment]
@chrisyip Sure thing

**Comment by digita1-Anal0g** [comment]
@chrisyip 

I believe I implemented a solution that would support the use-case where views is set to an array.  I added a unit test (and supporting code) as requested; however, during development, I couldn't get the existing tests to pass.  I initially thought it was environmental, but I encountered the same error on Windows and OS X.  The error is:

`TypeError: Cannot read property 'head' of undefined
   at addSelectState (D:\Source\express-dustjs\node_modules\dustjs-helpers\lib\dust-helpers.js:42:27)
   at Object.helpers.select (D:\Source\express-dustjs\node_modules\dustjs-helpers\lib\dust-helpers.js:322:17)
   at Chunk.helper (D:\Source\express-dustjs\node_modules\dustjs-linkedin\lib\dust.js:923:33)
   at body_1 (evalmachine.<anonymous>:1:397)
   at Chunk.block (D:\Source\express-dustjs\node_modules\dustjs-linkedin\lib\dust.js:876:14)
   at body_0 (evalmachine.<anonymous>:1:259)
   at done (D:\Source\express-dustjs\node_modules\dustjs-linkedin\lib\dust.js:176:13)
   at Object.dust.onLoad (D:\Source\express-dustjs\index.js:72:9)
   at D:\Source\express-dustjs\node_modules\dustjs-linkedin\lib\dust.js:182:18
   at Chunk.map (D:\Source\express-dustjs\node_modules\dustjs-linkedin\lib\dust.js:717:7)`

and have been stepping through the code listed in the stack trace to try to find the solution.  

Unfortunately, I haven't had much success and at this point I'm just banging my head against the wall.  It's possible that it's something really simple and my lack of understanding and/or command on dust isn't where it should be to spot it, but is this something you can take look at and resolve or possibly give me an idea on what to look at/for?

Currently, I suspect the error has something to do w/ the helpers.  If I comment out `require('./helpers/upper.js')` and set `userHelpers` to `false' in example/app.js, all unit tests pass except for `dust.helpers should support custom helpers`

Perhaps there was a breaking change between 1.5.0 and 1.7.x in dustjs-helpers and between dustjs-linkedin between 2.5.1 and 2.7.x?

**Comment by chrisyip** [comment]
@digita1-Anal0g hmm, wired. I will take a look at it when I have time. Thanks!

**Comment by chrisyip** [comment]
`dustjs-linkedin` did changed `Context` APIs, the solution is simple: upgrade `dustjs-linkedin` and `dustjs-helpers` to workable version.

This issue fixed in [v1.1.0](https://github.com/chrisyip/express-dustjs/releases/tag/v1.1.0).

Thank your!

**Pull request closed without merging**
